export const COLORS = [
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Black', hex: '#000000' },
  { name: 'Silver', hex: '#C0C0C0' },
  { name: 'Grey', hex: '#6E6E6E' },
  { name: 'Charcoal', hex: '#3B3B3B' },
  { name: 'Red', hex: '#C1272D' },
  { name: 'Maroon', hex: '#800000' },
  { name: 'Blue', hex: '#1E4E9E' },
  { name: 'Navy', hex: '#0B2545' },
  { name: 'Light Blue', hex: '#7FB3D5' },
  { name: 'Green', hex: '#1F8A43' },
  { name: 'Olive', hex: '#808000' },
  { name: 'Beige', hex: '#D6C6A8' },
  { name: 'Brown', hex: '#6B4C3B' },
  { name: 'Champagne', hex: '#ECD9C6' },
  { name: 'Gold', hex: '#C9A34A' },
  { name: 'Orange', hex: '#F08A24' },
  { name: 'Yellow', hex: '#FFD400' },
  { name: 'Purple', hex: '#6A3FA0' },
] as const
