const carData = {
  carBrands: [
    {
      name: 'Alfa Romeo',
      carModels: [
        '4C',
        '4C Spider',
        'Giulia',
        'Giulia Quadrifoglio',
        'Stelvio',
        'Stelvio Quadrifoglio',
        'Tonale',
        'Spider (Classic)',
        'GTV (Classic)',
        'Brera',
        'GT',
        '159',
        '166',
        '147',
        '156',
        '145',
        '146',
        '155',
        '164',
        '33',
        '75',
        '90',
        'SZ',
        'RZ',
        'Montreal',
        'Alfetta',
        'Alfasud',
        'Arna',
        'Sprint',
        'Milano',
        '6',
        '8C Competizione',
        '8C Spider',
        'MiTo',
        'Giulietta',
        '2000',
        '2600',
        '1900',
        '1750',
        '2300',
        'Alfa 6',
      ],
    },
    {
      name: 'Audi',
      carModels: [
        'A3',
        'A4',
        'A5',
        'A6',
        'A7',
        'A8',
        'S3',
        'S4',
        'S5',
        'S6',
        'S7',
        'S8',
        'RS3',
        'RS4',
        'RS5',
        'RS6',
        'RS7',
        'RS e-tron GT',
        'Q3',
        'Q5',
        'Q7',
        'Q8',
        'e-tron',
        'e-tron Sportback',
        'Q4 e-tron',
        'SQ5',
        'SQ7',
        'SQ8',
        'RS Q3',
        'RS Q8',
        'TT',
        'TTS',
        'TT RS',
        'R8',
        'A2',
        'A1',
        'Q2',
        'Allroad',
      ],
    },
    {
      name: 'BMW',
      carModels: [
        '1 Series',
        '2 Series',
        '3 Series',
        '4 Series',
        '5 Series',
        '6 Series',
        '7 Series',
        '8 Series',
        'X1',
        'X2',
        'X3',
        'X4',
        'X5',
        'X6',
        'X7',
        'XM',
        'Z4',
        'i3',
        'i4',
        'i7',
        'i8',
        'iX',
        'iX1',
        'iX3',
        'M2',
        'M3',
        'M4',
        'M5',
        'M8',
        'X3 M',
        'X4 M',
        'X5 M',
        'X6 M',
        'M240i',
        'M340i',
        'M440i',
        'M550i',
        'M760i',
        'M850i',
        '2002',
        'Z3',
        'Z8',
        'iX Flow',
      ],
    },
    {
      name: 'Chevrolet',
      carModels: [
        'Camaro',
        'Corvette',
        'Malibu',
        'Impala',
        'Spark',
        'Sonic',
        'Cruze',
        'Bolt EV',
        'Bolt EUV',
        'Equinox',
        'Trax',
        'Trailblazer',
        'Blazer',
        'Tahoe',
        'Suburban',
        'Traverse',
        'Silverado 1500',
        'Silverado 2500HD',
        'Silverado 3500HD',
        'Colorado',
        'Avalanche',
        'Express',
        'SSR',
        'HHR',
        'Volt',
        'Captiva',
        'Orlando',
        'Cobalt',
        'Aveo',
        'Monte Carlo',
        'SS',
      ],
    },
    {
      name: 'Chrysler',
      carModels: [
        '300',
        '300C',
        'Pacifica',
        'Voyager',
        'Pacifica Hybrid',
        '200',
        'Sebring',
        'PT Cruiser',
        'Crossfire',
        'Concorde',
        'LHS',
        'New Yorker',
        'Imperial',
        'LeBaron',
        'Fifth Avenue',
        'Town & Country',
        'Aspen',
        'Cirrus',
        'Prowler',
      ],
    },
    {
      name: 'Citroen',
      carModels: [
        'C3',
        'C4',
        'C5',
        'C5 Aircross',
        'C4 Picasso',
        'Grand C4 Picasso',
        'Berlingo',
        'Jumpy',
        'Spacetourer',
        'DS3',
        'DS4',
        'DS5',
        '2CV',
        'AX',
        'BX',
        'CX',
        'DS',
        'Dyane',
        'Evasion',
        'Saxo',
        'Visa',
        'XM',
        'Xantia',
        'Xsara',
        'C-Crosser',
        'C-Zero',
        'C1',
        'C2',
        'C3 Picasso',
        'C4 Cactus',
        'C6',
        'E-Mehari',
      ],
    },
    {
      name: 'Dacia',
      carModels: ['Sandero', 'Logan', 'Duster', 'Jogger', 'Spring', 'Lodgy', 'Dokker', 'Solenza', 'Supernova', '1300', '1310', '1410', 'Lodgy', 'Pick-Up'],
    },
    {
      name: 'Daewoo',
      carModels: [
        'Matiz',
        'Lanos',
        'Leganza',
        'Nubira',
        'Kalos',
        'Magnus',
        'Tacuma',
        'Evanda',
        'Winstorm',
        'Chairman',
        'Espero',
        'Prince',
        'Racer',
        'Tico',
        'Cielo',
        'Polonez',
        'Korando',
        'Musso',
        'Damas',
        'Labo',
        'Matiz Creative',
        'Lacetti',
        'Gentra',
      ],
    },
    {
      name: 'Daihatsu',
      carModels: [
        'Terios',
        'Sirion',
        'Materia',
        'Copen',
        'Cuore',
        'Charade',
        'Gran Max',
        'Move',
        'Tanto',
        'Mira',
        'Altis',
        'Xenia',
        'Pyzar',
        'Feroza',
        'Rocky',
        'YRV',
        'Applause',
        'Delta',
        'Zebra',
        'Fellow',
        'Midget',
        'Taft',
        'Wildcat',
        'Leeza',
        'Naked',
        'Opti',
        'MAX',
        'Boon',
        'Esse',
        'Hijet',
        'Atrai',
        'Mira e:S',
        'Cast',
        'Wake',
        'Mebius',
        'Thor',
        'Bego',
        'Be go',
        'Trevis',
        'Sonica',
      ],
    },
    {
      name: 'Fiat',
      carModels: [
        '500',
        '500e',
        '500X',
        '500L',
        'Panda',
        'Tipo',
        'Punto',
        'Bravo',
        'Linea',
        'Grande Punto',
        'Stilo',
        'Multipla',
        'Uno',
        'Palio',
        'Siena',
        'Strada',
        'Doblò',
        'Qubo',
        'Fiorino',
        'Fullback',
        '124 Spider',
        'Barchetta',
        'Coupe',
        'Croma',
        'Marea',
        'Tempra',
        'Regata',
        'Ritmo',
        '131',
        '128',
        '127',
        '126',
        '850',
        '600',
        '500 Topolino',
        'Dino',
        'X1/9',
        '238',
        '242',
        'Campagnola',
        'Freemont',
        'Sedici',
        'Punto Evo',
        'Idea',
        '500C',
      ],
    },
    {
      name: 'Ford',
      carModels: [
        'F-150',
        'F-150 Lightning',
        'Ranger',
        'Maverick',
        'Super Duty',
        'Mustang',
        'Mustang Mach-E',
        'Bronco',
        'Bronco Sport',
        'Escape',
        'Edge',
        'Explorer',
        'Expedition',
        'E-Transit',
        'EcoSport',
        'Flex',
        'Everest',
        'Focus',
        'Fusion',
        'Taurus',
        'Fiesta',
        'C-Max',
        'GT',
        'Shelby GT350',
        'Shelby GT500',
        'Raptor',
        'Thunderbird',
        'Model T',
        'Galaxie',
        'Fairlane',
        'Falcon',
        'Pinto',
        'Probe',
        'Contour',
        'Festiva',
        'Aspire',
        'Excursion',
        'Freestyle',
        'Five Hundred',
        'Crown Victoria',
        'LTD',
        'Torino',
        'Granada',
        'Windstar',
        'Aerostar',
      ],
    },
    {
      name: 'Honda',
      carModels: [
        'Accord',
        'Civic',
        'CR-V',
        'Pilot',
        'Odyssey',
        'HR-V',
        'Passport',
        'Ridgeline',
        'Fit',
        'Insight',
        'Clarity',
        'S2000',
        'Prelude',
        'Integra',
        'Legend',
        'NSX',
        'CR-Z',
        'Element',
        'Crosstour',
        'FR-V',
        'Jazz',
        'City',
        'Brio',
        'Amaze',
        'Mobilio',
        'BR-V',
        'CR-X',
        'Concerto',
        'Ascot',
        'Beat',
        'Capa',
        'Domani',
        'Horizon',
        'Lagreat',
        'Life',
        'Logo',
        'Orthia',
        'Partner',
        'Quint',
        "That's",
        'Vamos',
        'Z',
        'Acty',
        'Airwave',
        'Avancier',
        'Crossroad',
        'Edix',
        'Elysion',
        'EV Plus',
        'FCX Clarity',
        'Freed',
        'Inspire',
        'Jade',
        'N-Box',
        'N-One',
        'N-WGN',
        'N-Van',
        'Odyssey (Japan)',
        'Rafaga',
        'Saber',
        'Shuttle',
        'Stepwgn',
        'Stream',
        'Torneo',
        'Vezel',
        'Zest',
      ],
    },
    {
      name: 'Hyundai',
      carModels: [
        'Accent',
        'Elantra',
        'Sonata',
        'Ioniq',
        'Ioniq 5',
        'Ioniq 6',
        'Kona',
        'Tucson',
        'Santa Fe',
        'Palisade',
        'Venue',
        'Veloster',
        'Genesis Coupe',
        'Azera',
        'Equus',
        'Atos',
        'Getz',
        'i10',
        'i20',
        'i30',
        'i40',
        'Excel',
        'Pony',
        'Scoupe',
        'Stellar',
        'XG',
        'Terracan',
        'Veracruz',
        'Entourage',
        'H-1',
        'Grandeur',
        'Aslan',
        'Avante',
        'Casper',
        'Creta',
        'Eon',
        'Kona Electric',
        'Lafesta',
        'Marcia',
        'Maxcruz',
        'Mistra',
        'Nexo',
        'Porter',
        'Staria',
        'Tiburon',
        'Trajet',
        'Tuscani',
        'Solaris',
        'HB20',
        'ix20',
        'ix35',
        'ix55',
        'Bayon',
        'Alcazar',
      ],
    },
    {
      name: 'Jaguar',
      carModels: [
        'XE',
        'XF',
        'XJ',
        'F-PACE',
        'E-PACE',
        'I-PACE',
        'F-TYPE',
        'XK',
        'XKR',
        'XFR',
        'XJR',
        'S-Type',
        'X-Type',
        'Mark 2',
        'XJS',
        'XJ6',
        'XJ8',
        'XJ12',
        'XJ220',
        'XJR-15',
        'C-X75',
        'D-Type',
        'E-Type',
        'F-Type',
        'Mark IX',
        'Mark X',
        'SS 100',
        'XK120',
        'XK140',
        'XK150',
        'XKSS',
      ],
    },
    {
      name: 'Jeep',
      carModels: [
        'Wrangler',
        'Grand Cherokee',
        'Cherokee',
        'Compass',
        'Renegade',
        'Gladiator',
        'Wagoneer',
        'Grand Wagoneer',
        'Commander',
        'Patriot',
        'Liberty',
        'Commander',
        'CJ-5',
        'CJ-7',
        'CJ-8',
        'DJ-5',
        'FC-150',
        'FC-170',
        'Forward Control',
        'J-10',
        'J-20',
        'Jeepster',
        'Scrambler',
        'Willys',
        'Willys Wagon',
        'CJ-2A',
        'CJ-3A',
        'CJ-3B',
        'CJ-6',
        'CJ-10',
        'Comanche',
        'Dispatcher',
        'FC-170',
        'Fleetvan',
        'Honcho',
        'Hurricane',
        'J-2000',
        'J-200',
        'J-3000',
        'J-4000',
        'Jeepster Commando',
        'Kaiser',
        'M-170',
        'M-38',
        'M-38A1',
        'M-606',
        'M-715',
        'Mail Truck',
        'Military',
        'Pickup',
        'Pioneer',
        'Universal',
      ],
    },
    {
      name: 'Kia',
      carModels: [
        'Rio',
        'Forte',
        'Cerato',
        'Optima',
        'Stinger',
        'K5',
        'K8',
        'K9',
        'Picanto',
        'Morning',
        'Pride',
        'Ceed',
        'ProCeed',
        'Soul',
        'Seltos',
        'Niro',
        'EV6',
        'EV9',
        'Sportage',
        'Sorento',
        'Telluride',
        'Carnival',
        'Sedona',
        'Borrego',
        'Magentis',
        'Opirus',
        'Cadenza',
        'Quoris',
        'Ray',
        'Venga',
        'XCeed',
        'Joice',
        'Lotze',
        'Clarus',
        'Capital',
        'Concord',
        'Enterprise',
        'Potentia',
        'Retona',
        'Towner',
        'Besta',
        'Pregio',
        'Bongo',
        'K2500',
        'K2700',
        'K3000',
        'K3600',
        'K4000',
        'Mohave',
        "Ole'",
        'Carens',
        'Niro EV',
        'Niro PHEV',
        'Soul EV',
        'Stonic',
        'X-Trek',
        'KX1',
        'KX2',
        'KX3',
        'KX5',
        'KX7',
        'KX Cross',
      ],
    },
    {
      name: 'Lada',
      carModels: [
        'Granta',
        'Vesta',
        'XRAY',
        'Largus',
        'Niva',
        'Niva Legend',
        'Niva Travel',
        'Priora',
        'Kalina',
        'Samara',
        '2101',
        '2102',
        '2103',
        '2104',
        '2105',
        '2106',
        '2107',
        '2110',
        '2111',
        '2112',
        '2113',
        '2114',
        '2115',
        'Oka',
        '110',
        '111',
        '112',
        '1200',
        '1300',
        '1500',
        '1600',
        'Aleko',
        'Forma',
        'Silhouette',
        'Tarzan',
        'Urban',
        'C-Cross',
        '4x4 Urban',
        '4x4 Bronto',
        'Revolution',
        'C',
        'Elf',
        'Rapan',
        'Sputnik',
        'Taiga',
        'Vega',
        'Volga',
        '2108',
        '2109',
        '21099',
        '2116',
        '2117',
        '2118',
        '2119',
        '2120',
        '2121',
        '2123',
        '2129',
        '2329',
        '2330',
        'VAZ-1111',
        'VAZ-2120',
        'VAZ-2122',
        'VAZ-2129',
      ],
    },
    {
      name: 'Lancia',
      carModels: [
        'Ypsilon',
        'Delta',
        'Gamma',
        'Beta',
        'Flavia',
        'Fulvia',
        'Thema',
        'Kappa',
        'Lybra',
        'Phedra',
        'Musa',
        'Dedra',
        'Prisma',
        'A112',
        'Y10',
        'Zeta',
        'Stratos',
        '037',
        'Monte Carlo',
        'Aurelia',
        'Appia',
        'Flaminia',
        'Fulvia Coupé',
        'Lambda',
        'Ardea',
        'Aprilia',
        'Astura',
        'D20',
        'D23',
        'D24',
        'D25',
        'Beta Montecarlo',
        'Beta Coupé',
        'Beta Spider',
        'Beta HPE',
        'Beta Trevi',
        'Rally 037',
        'Delta Integrale',
        'Delta S4',
        'ECV',
        'LC1',
        'LC2',
        'Voyager',
        'Chrysler',
        'Thesis',
        'Voyager',
        'Hyena',
        'Dialogos',
      ],
    },
    {
      name: 'Land Rover',
      carModels: [
        'Defender',
        'Range Rover',
        'Range Rover Sport',
        'Range Rover Velar',
        'Range Rover Evoque',
        'Discovery',
        'Discovery Sport',
        'Freelander',
        'Freelander 2',
        'Series I',
        'Series II',
        'Series III',
        'Range Rover Classic',
        'Range Rover P38',
        'Range Rover L322',
        'Range Rover L405',
        'Range Rover Sport L320',
        'Range Rover Sport L494',
        'Defender 90',
        'Defender 110',
        'Defender 130',
        'Discovery 1',
        'Discovery 2',
        'Discovery 3',
        'Discovery 4',
        'Range Rover SVAutobiography',
        'Range Rover SVR',
        'Range Rover PHEV',
        'Range Rover Sport PHEV',
        'Range Rover Electric',
      ],
    },
    {
      name: 'Lexus',
      carModels: [
        'ES',
        'IS',
        'LS',
        'GS',
        'RC',
        'LC',
        'UX',
        'NX',
        'RX',
        'GX',
        'LX',
        'RZ',
        'LFA',
        'HS',
        'CT',
        'SC',
        'IS F',
        'RC F',
        'GS F',
        'LS F',
        'NX F Sport',
        'RX F Sport',
        'UX F Sport',
        'ES F Sport',
        'LS F Sport',
        'LC Convertible',
        'IS 300',
        'IS 350',
        'ES 250',
        'ES 300h',
        'ES 350',
        'LS 500',
        'LS 500h',
        'LS 600h',
        'GS 350',
        'GS 450h',
        'GS 460',
        'RC 350',
        'RC 300',
        'LC 500',
        'LC 500h',
        'UX 200',
        'UX 250h',
        'NX 200',
        'NX 300',
        'NX 350',
        'NX 450h+',
        'RX 350',
        'RX 450h',
        'RX 500h',
        'GX 460',
        'GX 550',
        'LX 570',
        'LX 600',
        'RZ 450e',
        'LFA 4.8',
      ],
    },
    {
      name: 'Mazda',
      carModels: [
        'Mazda2',
        'Mazda3',
        'Mazda6',
        'CX-3',
        'CX-30',
        'CX-5',
        'CX-50',
        'CX-60',
        'CX-70',
        'CX-8',
        'CX-9',
        'CX-90',
        'MX-5',
        'MX-30',
        'RX-7',
        'RX-8',
        'MPV',
        'B-Series',
        'BT-50',
        'Tribute',
        '626',
        '323',
        '929',
        'Cosmo',
        'Eunos 500',
        'Eunos 800',
        'Xedos 6',
        'Xedos 9',
        'Protege',
        'Premacy',
        'Verisa',
        'Atenza',
        'Axela',
        'Biante',
        'Carol',
        'Cronos',
        'Efini MS-6',
        'Efini MS-8',
        'Efini MS-9',
        'Eunos Cosmo',
        'Eunos Presso',
        'Flair',
        'Lantis',
        'Luce',
        'Millenia',
        'Persona',
        'Revue',
        'Roadster',
        'Savanna',
        'Scrum',
        'Sentia',
        'Spiano',
        'Titan',
        'VX-1',
      ],
    },
    {
      name: 'Mercedes Benz',
      carModels: [
        'A-Class',
        'B-Class',
        'C-Class',
        'E-Class',
        'S-Class',
        'CLA',
        'CLS',
        'SL',
        'SLC',
        'SLK',
        'SLR',
        'AMG GT',
        'GLA',
        'GLB',
        'GLC',
        'GLE',
        'GLS',
        'G-Class',
        'EQE',
        'EQS',
        'EQB',
        'EQA',
        'EQC',
        'Maybach',
        'CL',
        'CLC',
        'CLK',
        'R-Class',
        'V-Class',
        'X-Class',
        '190',
        '200',
        '220',
        '230',
        '250',
        '280',
        '300',
        '350',
        '380',
        '450',
        '500',
        '600',
        'Metris',
        'Sprinter',
        'Vaneo',
        'Viano',
        'Vito',
        'Citan',
        'T-Class',
        'EQ',
        'EQS SUV',
        'EQE SUV',
        'AMG SL',
        'AMG One',
      ],
    },
    {
      name: 'Mini',
      carModels: [
        'Cooper',
        'Cooper S',
        'John Cooper Works',
        'One',
        'Cooper D',
        'Cooper SD',
        'Electric',
        'Clubman',
        'Countryman',
        'Paceman',
        'Roadster',
        'Coupe',
        'Convertible',
        'GP',
        'Cooper SE',
        'Cooper E',
        'Cooper C',
        'Cooper D',
        'Cooper SD',
        'Cooper JCW',
        'Cooper S E',
        'Cooper SE Countryman',
        'Cooper S Countryman',
        'John Cooper Works Countryman',
        'Cooper S Clubman',
        'John Cooper Works Clubman',
        'Cooper S Paceman',
        'John Cooper Works Paceman',
        'Cooper S Roadster',
        'John Cooper Works Roadster',
        'Cooper S Coupe',
        'John Cooper Works Coupe',
        'Cooper S Convertible',
        'John Cooper Works Convertible',
        'Cooper S GP',
        'John Cooper Works GP',
        'Cooper S E Countryman',
        'Cooper SE Countryman',
        'Cooper S E Clubman',
        'Cooper SE Clubman',
      ],
    },
    {
      name: 'Mitsubishi',
      carModels: [
        'Lancer',
        'Outlander',
        'Eclipse Cross',
        'ASX',
        'Pajero',
        'Pajero Sport',
        'Triton',
        'Mirage',
        'Attrage',
        'Colt',
        'Galant',
        'Sigma',
        'Debonair',
        'Diamante',
        'Eclipse',
        'Endeavor',
        'FTO',
        'GTO',
        'i-MiEV',
        'L200',
        'L300',
        'L400',
        'Montero',
        'Nativa',
        'RVR',
        'Space Gear',
        'Space Star',
        'Space Wagon',
        'Starion',
        '3000GT',
        'Carisma',
        'Chariot',
        'Cordia',
        'Emeraude',
        'Expo',
        'Grandis',
        'Lancer Evolution',
        'Minica',
        'Minicab',
        'Mighty Max',
        'Proudia',
        'Raider',
        'Sapporo',
        'Savrin',
        'Tredia',
        'Xpander',
        'Delica',
        'eK',
        'i',
        'Jeep',
        'Town Box',
      ],
    },
    {
      name: 'Nissan',
      carModels: [
        'Altima',
        'Maxima',
        'Sentra',
        'Versa',
        'Leaf',
        'Z',
        'GT-R',
        'Rogue',
        'Murano',
        'Pathfinder',
        'Armada',
        'Kicks',
        'Frontier',
        'Titan',
        'Titan XD',
        'Ariya',
        'NV200',
        'NV Cargo',
        'NV Passenger',
        'Almera',
        'Bluebird',
        'Cedric',
        'Cima',
        'Cube',
        'Elgrand',
        'Fairlady',
        'Fuga',
        'Gloria',
        'Juke',
        'Latio',
        'Laurel',
        'March',
        'Micra',
        'Note',
        'Pulsar',
        'Qashqai',
        'Quest',
        'Rasheen',
        'Safari',
        'Silvia',
        'Skyline',
        'Stagea',
        'Sunny',
        'Teana',
        'Terrano',
        'Tiida',
        'Vanette',
        'Wingroad',
        'X-Trail',
        'Xterra',
        '370Z',
        '180SX',
        '200SX',
        '240SX',
        '300ZX',
        'B14',
        'B15',
        'D21',
        'D22',
        'N16',
        'N17',
        'NP300',
        'S13',
        'S14',
        'S15',
        'T30',
        'T31',
        'T32',
        'U13',
        'Y11',
        'Y12',
      ],
    },
    {
      name: 'Opel',
      carModels: [
        'Adam',
        'Ampera',
        'Ampera-e',
        'Antara',
        'Ascona',
        'Astra',
        'Calibra',
        'Campo',
        'Cascada',
        'Combo',
        'Commodore',
        'Corsa',
        'Crossland',
        'Frontera',
        'Grandland',
        'GT',
        'Insignia',
        'Kadett',
        'Karl',
        'Manta',
        'Meriva',
        'Mokka',
        'Monterey',
        'Monza',
        'Movano',
        'Omega',
        'Rekord',
        'Senator',
        'Signum',
        'Sintra',
        'Speedster',
        'Tigra',
        'Vectra',
        'Vivaro',
        'Zafira',
        'Agila',
        'Arena',
        'Diplomat',
        'Flextreme',
        'GTC',
        'Kapitän',
        'Olympia',
        'Rallye',
        'Superboss',
        'Vita',
        'Admiral',
        'Chevette',
        'Commodore',
        'Kapitän',
        'Monza',
        'P4',
        'Rekord',
        '6',
        '10',
        '12',
        '14',
        '15',
        '17',
        '19',
        '21',
        '24',
        '30',
        'Kapitan',
        'P1',
        'P2',
        'P3',
        'P6',
      ],
    },
    {
      name: 'Peugeot',
      carModels: [
        '108',
        '208',
        '308',
        '408',
        '508',
        '2008',
        '3008',
        '5008',
        'Rifter',
        'Traveller',
        'Partner',
        'Expert',
        'Boxer',
        '106',
        '205',
        '206',
        '207',
        '306',
        '307',
        '405',
        '406',
        '407',
        '605',
        '607',
        '806',
        '807',
        '1007',
        '4007',
        '4008',
        'RCZ',
        'iOn',
        'Bipper',
        'Hoggar',
        'Proxima',
        'Quark',
        'Velv',
        '504',
        '505',
        '604',
        '104',
        '204',
        '304',
        '404',
        '504',
        '604',
        '904',
        '905',
        'Touareg',
        'J5',
        'J7',
        'J9',
        'D3',
        'D4',
        'P4',
        'P5',
        'P6',
        'P7',
        'P8',
        'P9',
        'VLV',
        'Type 15',
        'Type 25',
        'Type 33',
        'Type 36',
        'Type 56',
        'Type 57',
        'Type 58',
        'Type 63',
        'Type 65',
        'Type 66',
        'Type 71',
        'Type 72',
        'Type 76',
        'Type 77',
        'Type 78',
        'Type 81',
        'Type 82',
        'Type 83',
        'Type 84',
        'Type 85',
        'Type 86',
        'Type 87',
        'Type 88',
        'Type 89',
        'Type 90',
        'Type 91',
        'Type 92',
        'Type 93',
        'Type 94',
        'Type 95',
        'Type 96',
        'Type 97',
        'Type 98',
        'Type 99',
        'Type 100',
        'Type 101',
        'Type 102',
        'Type 103',
        'Type 104',
        'Type 105',
        'Type 106',
        'Type 107',
        'Type 108',
        'Type 109',
        'Type 110',
      ],
    },
    {
      name: 'Porsche',
      carModels: [
        '911',
        '718 Boxster',
        '718 Cayman',
        'Taycan',
        'Panamera',
        'Cayenne',
        'Macan',
        '918 Spyder',
        'Carrera GT',
        '959',
        '356',
        '550 Spyder',
        '912',
        '914',
        '924',
        '928',
        '944',
        '968',
        'Boxster',
        'Cayman',
        '911 GT1',
        '911 GT2',
        '911 GT3',
        '911 R',
        '911 Turbo',
        '911 Carrera',
        '911 Targa',
        '911 Speedster',
        '911 Dakar',
        'Mission X',
        'Vision 357',
        'Cayenne Coupe',
        'Macan T',
        'Taycan Cross Turismo',
        'Taycan Sport Turismo',
        'Taycan Turbo',
        'Taycan Turbo S',
        'Panamera Turbo',
        'Panamera GTS',
        'Panamera Sport Turismo',
        'Panamera Turbo S',
        'Panamera 4',
        'Panamera 4S',
        'Panamera 4S E-Hybrid',
        'Panamera Turbo S E-Hybrid',
        'Cayenne Turbo',
        'Cayenne Turbo S',
        'Cayenne GTS',
        'Cayenne S',
        'Cayenne E-Hybrid',
        'Macan S',
        'Macan GTS',
        'Macan Turbo',
        '911 GT3 RS',
        '911 GT3 Touring',
        '911 Turbo S',
        '911 Targa 4S',
        '911 Carrera 4S',
        '911 Carrera S',
        '911 Carrera',
        '718 Spyder',
        '718 Cayman GT4',
        '718 Boxster GTS',
        '718 Cayman GTS',
      ],
    },
    {
      name: 'Renault',
      carModels: [
        'Clio',
        'Megane',
        'Captur',
        'Kadjar',
        'Arkana',
        'Austral',
        'Scenic',
        'Talisman',
        'Zoe',
        'Twingo',
        'Kangoo',
        'Trafic',
        'Master',
        'Express',
        'Alpine A110',
        'Alpine A310',
        'Alpine A610',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '25',
        '30',
        'Fuego',
        'Laguna',
        'Safrane',
        'Vel Satis',
        'Avantime',
        'Wind',
        'Modus',
        'Grand Modus',
        'Koleos',
        'Fluence',
        'Latitude',
        'Symbol',
        'Logan',
        'Sandero',
        'Duster',
        'Lodgy',
        'Dokker',
        'Espace',
        'Grand Espace',
        'Kangoo Express',
        'Master Fourgon',
        'R4',
        'R5',
        'R6',
        'R7',
        'R8',
        'R9',
        'R10',
        'R11',
        'R12',
        'R14',
        'R15',
        'R16',
        'R17',
        'R18',
        'R19',
        'R20',
        'R21',
        'R25',
        'R30',
        'R4 F4',
        'R4 F6',
        'R5 Turbo',
        'R5 Alpine',
        'R5 Maxi',
        'R5 Gordini',
        'R5 Campus',
        'R5 Supercinq',
        'R5 Turbo 2',
        'R5 GT Turbo',
        'R5 Alpine Turbo',
        'R5 Copa',
        'R5 Monaco',
        'R5 Raid',
        'R5 TL',
        'R5 GTL',
        'R5 TS',
        'R5 Automatic',
        'R5 TX',
        'R5 LS',
        'R5 GT',
        'R5 Turbo',
        'R5 Alpine',
        'R5 Maxi',
        'R5 Gordini',
        'R5 Campus',
        'R5 Supercinq',
        'R5 Turbo 2',
        'R5 GT Turbo',
        'R5 Alpine Turbo',
        'R5 Copa',
        'R5 Monaco',
        'R5 Raid',
        'R5 TL',
        'R5 GTL',
        'R5 TS',
        'R5 Automatic',
        'R5 TX',
        'R5 LS',
        'R5 GT',
      ],
    },
    {
      name: 'Rover',
      carModels: [
        '25',
        '45',
        '75',
        '200',
        '400',
        '600',
        '800',
        '100',
        '2000',
        '2200',
        '3500',
        'SD1',
        'P4',
        'P5',
        'P6',
        'Streetwise',
        'CityRover',
        'Metro',
        'Montego',
        'Maestro',
        '600',
        '800',
        '100',
        '200',
        '400',
        '600',
        '800',
        'Tourer',
        'Cabriolet',
        'Coupe',
        'Vitesse',
        'Vanden Plas',
        'Sterling',
        'Tomcat',
        'BRM',
        'TC',
        'GT',
        'S',
        'P3',
        'P4',
        'P5',
        'P6',
        'SD1',
        '216',
        '414',
        '416',
        '418',
        '620',
        '623',
        '825',
        '827',
        '820',
        '825',
        '827',
        'Streetwise',
        'CityRover',
        'Metro',
        'Montego',
        'Maestro',
        '600',
        '800',
        '100',
        '200',
        '400',
        '600',
        '800',
        'Tourer',
        'Cabriolet',
        'Coupe',
        'Vitesse',
        'Vanden Plas',
        'Sterling',
        'Tomcat',
        'BRM',
        'TC',
        'GT',
        'S',
        'P3',
        'P4',
        'P5',
        'P6',
        'SD1',
      ],
    },
    {
      name: 'Saab',
      carModels: [
        '9-3',
        '9-5',
        '900',
        '9000',
        '93',
        '95',
        '96',
        '99',
        '9-2X',
        '9-4X',
        '9-7X',
        'Sonett',
        'Monte Carlo',
        'Sport',
        'GT',
        'GT750',
        'GT850',
        'Formula',
        'Formula Junior',
      ],
    },
    {
      name: 'Seat',
      carModels: [
        'Ibiza',
        'Leon',
        'Arona',
        'Ateca',
        'Tarraco',
        'Alhambra',
        'Altea',
        'Cordoba',
        'Exeo',
        'Mii',
        'Toledo',
        'Arosa',
        'Marbella',
        'Ronda',
        'Malaga',
        'Fura',
        'Inca',
        '133',
        '850',
        '1200',
        '1430',
        '1500',
        '124',
        '127',
        '128',
        '131',
        '132',
        '1400',
        '600',
        '800',
        '1000',
        '1100',
        '1200',
        '1400',
        '1500',
        '1600',
        '1800',
        '2000',
        'Cupra',
        'Cupra Formentor',
        'Cupra Leon',
        'Cupra Ateca',
        'Cupra Born',
        'Cupra Tavascan',
      ],
    },
    {
      name: 'Skoda',
      carModels: [
        'Fabia',
        'Octavia',
        'Superb',
        'Kodiaq',
        'Karoq',
        'Kamiq',
        'Enyaq',
        'Enyaq Coupé',
        'Rapid',
        'Yeti',
        'Citigo',
        'Roomster',
        'Praktik',
        '120',
        '130',
        '135',
        '136',
        '1000 MB',
        '100',
        '110',
        '120',
        '130',
        'Favorit',
        'Felicia',
        'Forman',
        'Popular',
        'Scala',
        'Octavia RS',
        'Superb Sportline',
        'Kodiaq RS',
        'Enyaq RS',
        'Octavia Scout',
        'Yeti Outdoor',
        '105',
        '120',
        '125',
        '130',
        '135',
        '136',
        '1000 MBX',
        '1100',
        '1200',
        '1300',
        '1400',
        'Octavia vRS',
        'Fabia RS',
        'Superb L&K',
        'Octavia L&K',
        'Octavia Combi',
        'Superb Combi',
        'Octavia GreenLine',
        'Superb GreenLine',
        'Octavia Laurin & Klement',
        'Superb Laurin & Klement',
      ],
    },
    {
      name: 'Smart',
      carModels: [
        'Fortwo',
        'Forfour',
        'Roadster',
        'Crossblade',
        'Fortwo Electric Drive',
        'EQ Fortwo',
        'EQ Forfour',
        'Fortwo Cabrio',
        'Fortwo Coupe',
        'Fortwo Brabus',
        'Forfour Brabus',
        'Roadster Coupe',
        'Roadster Brabus',
        'Fortwo ED',
        'Fortwo Prime',
        'Fortwo Pulse',
        'Fortwo Passion',
        'Fortwo Pure',
        'Fortwo Proxy',
        'Fortwo Nightorange',
        'Fortwo Blackseries',
        'Fortwo Exclusive',
        'Fortwo Style',
        'Fortwo Sport',
        'Fortwo Limited',
        'Fortwo Star',
        'Fortwo Edition',
        'Fortwo Collector',
        'Fortwo Finale',
        'Fortwo Ultimate',
      ],
    },
    {
      name: 'Subaru',
      carModels: [
        'Outback',
        'Forester',
        'Crosstrek',
        'Impreza',
        'Legacy',
        'Ascent',
        'BRZ',
        'Solterra',
        'WRX',
        'WRX STI',
        'STI',
        'WRX TR',
        'Baja',
        'Tribeca',
        'SVX',
        'XT',
        'Justy',
        'Leone',
        'Loyale',
        'Domingo',
        'Vivio',
        'Exiga',
        'Pleo',
        'Sambar',
        'Traviq',
        'Dex',
        'Lucra',
        'Levorg',
        'Stella',
        '360',
        '1000',
        '1500',
        'FF-1',
        'FF-1 G',
        'FF-1 Star',
        'R-2',
        'R-2 SS',
        'Outback Wilderness',
        'Forester Wilderness',
        'Crosstrek Wilderness',
        'WRX tS',
        'BRZ tS',
      ],
    },
    {
      name: 'Suzuki',
      carModels: [
        'Swift',
        'Ignis',
        'Baleno',
        'Celerio',
        'Jimny',
        'Vitara',
        'S-Cross',
        'Across',
        'Alto',
        'Wagon R',
        'Liana',
        'Kizashi',
        'Grand Vitara',
        'SX4',
        'XL7',
        'Samurai',
        'Sidekick',
        'Equator',
        'Carry',
        'Every',
        'Landy',
        'Solio',
        'Spacia',
        'Hustler',
        'Xbee',
        'X-90',
        'Cappuccino',
        'Cervo',
        'Kei',
        'Lapin',
        'MR Wagon',
        'Palette',
        'Twin',
        'Verona',
        'Aerio',
        'Esteem',
        'Forenza',
        'Reno',
        'Cultus',
        'Cultus Crescent',
        'Fronte',
        'Mighty Boy',
        'SJ',
        'SJ410',
        'SJ413',
        'Super Carry',
        'Carry',
        'APV',
        'Ertiga',
        'XL-7',
        'Katana',
        'GSX',
        'GSX-R',
        'GSX-S',
        'V-Strom',
        'Boulevard',
        'Intruder',
        'Burgman',
        'Address',
        'Lets',
        'Bandit',
        'Gixxer',
        'Hayabusa',
        'VanVan',
      ],
    },
    {
      name: 'Tesla',
      carModels: [
        'Model S',
        'Model 3',
        'Model X',
        'Model Y',
        'Cybertruck',
        'Roadster',
        'Model S Plaid',
        'Model X Plaid',
        'Model 3 Performance',
        'Model Y Performance',
        'Roadster 2.0',
        'Semi',
        'Model S Long Range',
        'Model X Long Range',
        'Model 3 Long Range',
        'Model Y Long Range',
        'Model S Standard Range',
        'Model 3 Standard Range',
        'Model Y Standard Range',
        'Model S Raven',
        'Model X Raven',
        'Cybertruck Tri Motor',
        'Cybertruck Dual Motor',
        'Cybertruck Single Motor',
        'Model S Ludicrous',
        'Model X Ludicrous',
      ],
    },
    {
      name: 'Toyota',
      carModels: [
        'Camry',
        'Corolla',
        'Prius',
        'RAV4',
        'Highlander',
        'Sienna',
        'Tacoma',
        'Tundra',
        '4Runner',
        'Sequoia',
        'Land Cruiser',
        'C-HR',
        'Venza',
        'bZ4X',
        'GR86',
        'GR Supra',
        'GR Corolla',
        'GR Yaris',
        'Prius Prime',
        'RAV4 Prime',
        'bZ3',
        'bZ4X',
        'Mirai',
        'FJ Cruiser',
        'Tundra Hybrid',
        'Tacoma TRD',
        '4Runner TRD',
        'Land Cruiser Prado',
        'GR Supra',
        'GR Corolla',
        'GR Yaris',
        'GR86',
        'Supra',
        '86',
        'Avalon',
        'Yaris',
        'Celica',
        'MR2',
        'Echo',
        'Matrix',
        'FJ Cruiser',
        'Previa',
        'Cressida',
        'Corona',
        'Hilux',
        'Fortuner',
        'Innova',
        'Land Cruiser 70',
        'Land Cruiser 300',
        'Proace',
        'Proace City',
        'Aygo',
        '2000GT',
        'Corolla AE86',
        'Celica GT-Four',
        'Supra MKIV',
        'Crown',
        'Century',
        'Soarer',
        'Chaser',
        'Mark II',
      ],
    },
    {
      name: 'Trabant',
      carModels: [
        'P50',
        'P60',
        '601',
        '1.1',
        '600',
        '601 Universal',
        '601 Kübel',
        '601 Tramp',
        '601 S',
        '601 DeLuxe',
        '601 Hycomat',
        'P50 Limousine',
        'P50 Universal',
        'P60 Limousine',
        'P60 Universal',
        'P50 Kübel',
        'P60 Kübel',
        'P50 Sport',
        'P60 Sport',
        'P603',
        'P601',
        'P600',
        'P601 S',
        'P601 DeLuxe',
        'P601 Universal',
        'P601 Kübel',
        'P601 Tramp',
        'P601 Hycomat',
        'P601 Rallye',
        'P601 Favorit',
        'P601 Junior',
        'P601 Standard',
        'P601 Luxus',
        'P601 Special',
        'P601 Export',
        'P601 Famili',
        'P601 Camping',
        'P601 Piccolo',
        'P601 Formel',
        'P601 Trend',
        'P601 Classic',
        'P601 Vintage',
        'P601 Retro',
        'P601 Oldtimer',
        'P601 Youngtimer',
      ],
    },
    {
      name: 'Volkswagen',
      carModels: [
        'Golf',
        'Jetta',
        'Passat',
        'Arteon',
        'Tiguan',
        'Atlas',
        'Taos',
        'ID.4',
        'ID.3',
        'ID. Buzz',
        'Beetle',
        'Polo',
        'T-Roc',
        'T-Cross',
        'Touran',
        'Sharan',
        'Caddy',
        'Amarok',
        'Transporter',
        'Caravelle',
        'California',
        'Scirocco',
        'Eos',
        'CC',
        'Phaeton',
        'Lupo',
        'Fox',
        'Up',
        'XL1',
        'Karmann Ghia',
        'Type 1',
        'Type 2',
        'Type 3',
        'Type 4',
        '181',
        '411',
        '412',
        'Dasher',
        'Rabbit',
        'Corrado',
        'Santana',
        'Vento',
        'Bora',
        'Lavida',
        'Sagitar',
        'Lamando',
        'Teramont',
        'Tharu',
        'Viloran',
        'ID.5',
        'ID.6',
        'ID.7',
        'ID.8',
        'ID.9',
        'ID.10',
        'ID.11',
        'ID.12',
        'ID.13',
        'ID.14',
        'ID.15',
        'Golf GTI',
        'Golf R',
        'Golf SportWagen',
        'Golf Alltrack',
        'Jetta GLI',
        'Passat GT',
        'Arteon R',
        'Tiguan R',
        'Atlas Cross Sport',
        'Taos SEL',
        'ID.4 Pro',
        'ID.4 AWD',
        'ID. Buzz Cargo',
        'ID. Buzz Passenger',
      ],
    },
    {
      name: 'Volvo',
      carModels: [
        'S60',
        'S90',
        'V60',
        'V90',
        'XC40',
        'XC60',
        'XC90',
        'C40',
        'EX30',
        'EX90',
        'EM90',
        'S40',
        'V40',
        'V50',
        'S80',
        'C30',
        'C70',
        'XC70',
        'V70',
        'S70',
        '850',
        '940',
        '240',
        '740',
        'P1800',
        'PV544',
        'Amazon',
        'Duett',
        '140',
        '164',
        '1800ES',
        '262C',
        'XC40 Recharge',
        'C40 Recharge',
        'EX30',
        'EX90',
        'EM90',
        'S60 Polestar',
        'S90 Polestar',
        'V60 Polestar',
        'XC60 Polestar',
        'XC90 Polestar',
      ],
    },
  ],
}

export default carData
